swagger: '2.0'
info:
  title: 'Challenge VidaTec'
  version: 0.0.0
  description: 'Example documentation for VidaTec'
  contact:
    email: "carlosdanielmou@gmail.com"
paths:
  /credit:
    post:
      tags:
        - Transaction
      summary: Credit
      description: Credit
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: amount
          schema:
            properties:
              amount:
                type: number
                description: amount.
            type: object
            required:
              - amount
      responses:
        '200':
          description: 'successful operation'
          schema:
            $ref: "#/definitions/Transaction"
  /debit:
    post:
      tags:
        - Transaction
      summary: Debit
      description: Debit
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: amount
          schema:
            properties:
              amount:
                type: number
                description: amount.
            type: object
            required:
              - amount
      responses:
        '200':
          description: 'successful operation'
          schema:
            $ref: "#/definitions/Transaction"
  /detail:
    get:
      tags:
        - Transaction
      summary: Detail
      description: Detail
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          schema:
            type: object
            properties:
              balance:
                type: number
                description: Account Balance.
              transactions:
                type: array
                items:
                  $ref: "#/definitions/Transaction"
          description: 'successful operation'
definitions:
  Transaction:
    type: "object"
    properties:
      id:
        type: "string"
      amount:
        type: "number"
      status:
        type: "string"
        description: "Transaction type"
        enum:
          - "Credit"
          - "Debit"
      date:
        type: "string"
        format: "date-time"
